-- Deploy YOUR_SQITCH_PROJECT:create_user_tokens to pg
-- requires: create_users

BEGIN;

CREATE TABLE user_tokens (
    id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                  INTEGER     NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    access_token             TEXT        NOT NULL UNIQUE,
    refresh_token            TEXT        NOT NULL UNIQUE,
    access_token_expires_at  TIMESTAMPTZ NOT NULL,
    refresh_token_expires_at TIMESTAMPTZ NOT NULL,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    is_active                BOOLEAN     NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_user_tokens_user_id       ON user_tokens(user_id);
CREATE INDEX idx_user_tokens_access_token  ON user_tokens(access_token);
CREATE INDEX idx_user_tokens_refresh_token ON user_tokens(refresh_token);
CREATE INDEX idx_user_tokens_active        ON user_tokens(is_active);

COMMIT;
