-- Deploy YOUR_SQITCH_PROJECT:create_users to pg

BEGIN;

CREATE TABLE users (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email            TEXT    NOT NULL UNIQUE,
    name             TEXT,
    hashed_password  TEXT    NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_active_at   TIMESTAMPTZ
);

CREATE INDEX idx_users_email ON users(email);

-- Keep updated_at fresh automatically
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

COMMIT;
